import type { Plan } from '@/types'

const L = 100_000 // 1 lakh
const CR = 10_000_000 // 1 crore

/**
 * Mock plan catalog.
 *
 * Why mocked instead of a public API: insurance plans need domain-specific
 * shapes (cover ranges, term options, premium rates, nominee rules) that
 * product/store APIs don't model. Hand-authored data keeps the quote maths and
 * the journey realistic. Plans reference partners by id, so the home catalog is
 * filtered to whatever the active partner offers.
 */
export const plans: Plan[] = [
  {
    id: 'term-life-secure',
    name: 'SecureLife Term Plan',
    category: 'Term Life',
    tagline: 'High cover, low premium, total peace of mind.',
    description:
      'A pure-protection term plan that pays a lump sum to your family if something happens to you during the policy term. Designed for maximum cover at an affordable premium.',
    featured: true,
    partnerIds: ['aegis', 'verdant', 'nimbus'],
    icon: '🛡️',
    coverage: { min: 25 * L, max: 5 * CR, step: 25 * L, default: 1 * CR },
    termOptions: [10, 15, 20, 25, 30],
    baseRatePerLakh: 22,
    benefits: [
      'Cover up to ₹5 crore',
      'Tax benefits under 80C & 10(10D)',
      'Optional accidental death rider',
      'Terminal illness benefit included',
    ],
    coverageDetails: [
      { label: 'Death benefit', value: 'Full sum assured to nominee' },
      { label: 'Terminal illness', value: 'Accelerated payout' },
      { label: 'Tax saving', value: 'Up to ₹46,800/yr' },
    ],
    exclusions: ['Suicide within first 12 months', 'Pre-existing undisclosed conditions'],
    rating: 4.7,
    claimSettlementRatio: 98.6,
  },
  {
    id: 'term-life-max',
    name: 'MaxProtect Term Plus',
    category: 'Term Life',
    tagline: 'Return-of-premium term cover with riders.',
    description:
      'A term plan that returns all premiums paid if you survive the policy term, combining protection with savings.',
    featured: false,
    partnerIds: ['aegis', 'solaris'],
    icon: '💼',
    coverage: { min: 50 * L, max: 3 * CR, step: 25 * L, default: 75 * L },
    termOptions: [15, 20, 25, 30],
    baseRatePerLakh: 41,
    benefits: [
      'Return of premium on survival',
      'Critical illness rider available',
      'Waiver of premium on disability',
      'Loyalty additions',
    ],
    coverageDetails: [
      { label: 'Death benefit', value: 'Full sum assured to nominee' },
      { label: 'Maturity benefit', value: 'All premiums returned' },
      { label: 'Critical illness', value: 'Optional rider' },
    ],
    exclusions: ['Suicide within first 12 months', 'Hazardous activities unless declared'],
    rating: 4.4,
    claimSettlementRatio: 97.9,
  },
  {
    id: 'health-shield-family',
    name: 'FamilyShield Health Cover',
    category: 'Health',
    tagline: 'One policy that protects the whole family.',
    description:
      'A comprehensive family floater health plan covering hospitalisation, day-care procedures and pre/post-hospitalisation expenses for everyone under a single sum insured.',
    featured: true,
    partnerIds: ['aegis', 'verdant'],
    icon: '❤️',
    coverage: { min: 5 * L, max: 1 * CR, step: 5 * L, default: 10 * L },
    termOptions: [1, 2, 3],
    baseRatePerLakh: 520,
    benefits: [
      'Family floater — covers up to 6 members',
      'Cashless treatment at 10,000+ hospitals',
      'No-claim bonus up to 100%',
      'Free annual health check-up',
    ],
    coverageDetails: [
      { label: 'Room rent', value: 'No capping' },
      { label: 'Pre/post hospitalisation', value: '60 / 90 days' },
      { label: 'Day-care procedures', value: '500+ covered' },
      { label: 'Restoration', value: '100% sum insured' },
    ],
    exclusions: ['Cosmetic treatment', 'Pre-existing diseases (2-yr waiting period)'],
    rating: 4.6,
    claimSettlementRatio: 96.2,
  },
  {
    id: 'health-care-plus',
    name: 'CarePlus Individual Health',
    category: 'Health',
    tagline: 'Solid individual cover that grows every year.',
    description:
      'An individual health plan with generous sum insured, restoration benefit and a strong no-claim bonus for staying healthy.',
    featured: false,
    partnerIds: ['solaris', 'nimbus'],
    icon: '🏥',
    coverage: { min: 3 * L, max: 50 * L, step: 1 * L, default: 5 * L },
    termOptions: [1, 2, 3],
    baseRatePerLakh: 610,
    benefits: [
      'Restoration of cover once a year',
      'No-claim bonus up to 50%',
      'Cashless network hospitals',
      'AYUSH treatment covered',
    ],
    coverageDetails: [
      { label: 'Room rent', value: 'Single private room' },
      { label: 'Pre/post hospitalisation', value: '30 / 60 days' },
      { label: 'No-claim bonus', value: 'Up to 50%' },
    ],
    exclusions: ['Cosmetic treatment', 'Self-inflicted injuries'],
    rating: 4.3,
    claimSettlementRatio: 95.1,
  },
  {
    id: 'motor-drive-secure',
    name: 'DriveSecure Car Insurance',
    category: 'Motor',
    tagline: 'Comprehensive cover with zero-depreciation.',
    description:
      'A comprehensive motor policy covering own damage and third-party liability, with add-ons like zero-depreciation and roadside assistance.',
    featured: true,
    partnerIds: ['solaris', 'aegis'],
    icon: '🚗',
    coverage: { min: 1 * L, max: 50 * L, step: 50_000, default: 8 * L },
    termOptions: [1, 2, 3],
    baseRatePerLakh: 2800,
    benefits: [
      'Own damage + third-party liability',
      'Zero-depreciation add-on',
      '24x7 roadside assistance',
      'Cashless garages nationwide',
    ],
    coverageDetails: [
      { label: 'Own damage', value: 'Up to IDV' },
      { label: 'Third-party liability', value: 'As per Motor Act' },
      { label: 'Roadside assistance', value: 'Included' },
    ],
    exclusions: ['Driving without licence', 'Driving under influence', 'Normal wear and tear'],
    rating: 4.2,
    claimSettlementRatio: 94.5,
  },
  {
    id: 'travel-globe',
    name: 'GlobeSafe Travel Insurance',
    category: 'Travel',
    tagline: 'Worry-free international travel cover.',
    description:
      'Single-trip travel insurance covering medical emergencies, trip cancellation, lost baggage and passport assistance worldwide.',
    featured: false,
    partnerIds: ['verdant', 'nimbus', 'solaris'],
    icon: '✈️',
    coverage: { min: 2 * L, max: 40 * L, step: 1 * L, default: 8 * L },
    termOptions: [1, 2, 3],
    baseRatePerLakh: 180,
    benefits: [
      'Emergency medical cover abroad',
      'Trip cancellation & delay',
      'Lost baggage & passport assistance',
      'Cashless hospitalisation overseas',
    ],
    coverageDetails: [
      { label: 'Medical emergency', value: 'Up to sum insured' },
      { label: 'Baggage loss', value: 'Up to ₹50,000' },
      { label: 'Trip cancellation', value: 'Covered' },
    ],
    exclusions: ['Pre-existing conditions', 'Adventure sports unless added'],
    rating: 4.5,
    claimSettlementRatio: 93.8,
  },
  {
    id: 'home-secure',
    name: 'HomeSecure Property Cover',
    category: 'Home',
    tagline: 'Protect your home and everything in it.',
    description:
      'Covers your home structure and contents against fire, theft, natural disasters and more.',
    featured: false,
    partnerIds: ['aegis', 'nimbus'],
    icon: '🏠',
    coverage: { min: 5 * L, max: 2 * CR, step: 5 * L, default: 25 * L },
    termOptions: [1, 3, 5],
    baseRatePerLakh: 75,
    benefits: [
      'Fire & allied perils cover',
      'Burglary & theft protection',
      'Natural disaster cover',
      'Contents & valuables protection',
    ],
    coverageDetails: [
      { label: 'Structure', value: 'Up to sum insured' },
      { label: 'Contents', value: 'Optional add-on' },
      { label: 'Natural disasters', value: 'Earthquake, flood, storm' },
    ],
    exclusions: ['Wear and tear', 'War and nuclear perils'],
    rating: 4.1,
    claimSettlementRatio: 92.4,
  },
  {
    id: 'health-senior',
    name: 'SeniorCare Health Plan',
    category: 'Health',
    tagline: 'Designed for parents and senior citizens.',
    description:
      'A specialised health plan for senior citizens with pre-existing disease cover after a short waiting period and domiciliary hospitalisation.',
    featured: false,
    partnerIds: ['verdant'],
    icon: '🧓',
    coverage: { min: 3 * L, max: 25 * L, step: 1 * L, default: 5 * L },
    termOptions: [1, 2],
    baseRatePerLakh: 1150,
    benefits: [
      'Pre-existing cover after 1 year',
      'Domiciliary hospitalisation',
      'No pre-policy medical up to 60',
      'Annual health check-up',
    ],
    coverageDetails: [
      { label: 'Entry age', value: 'Up to 75 years' },
      { label: 'Pre-existing waiting', value: '12 months' },
      { label: 'Co-payment', value: '10–20%' },
    ],
    exclusions: ['Cosmetic treatment', 'Non-allopathic treatment unless specified'],
    rating: 4.0,
    claimSettlementRatio: 95.7,
  },
  {
    id: 'term-life-young',
    name: 'YoungStart Term Cover',
    category: 'Term Life',
    tagline: 'Lock in low premiums while you are young.',
    description:
      'A term plan tailored for first-jobbers — low entry premium that stays level for the entire term.',
    featured: true,
    partnerIds: ['nimbus'],
    icon: '🌱',
    coverage: { min: 25 * L, max: 2 * CR, step: 25 * L, default: 50 * L },
    termOptions: [10, 20, 30, 40],
    baseRatePerLakh: 16,
    benefits: [
      'Lowest entry premium',
      'Level premium for life of policy',
      'Increase cover at life milestones',
      'Fully digital onboarding',
    ],
    coverageDetails: [
      { label: 'Death benefit', value: 'Full sum assured to nominee' },
      { label: 'Premium', value: 'Level for entire term' },
      { label: 'Top-up', value: 'On marriage / childbirth' },
    ],
    exclusions: ['Suicide within first 12 months'],
    rating: 4.8,
    claimSettlementRatio: 98.1,
  },
  {
    id: 'travel-student',
    name: 'StudyAbroad Travel Cover',
    category: 'Travel',
    tagline: 'Cover for students studying overseas.',
    description:
      'Long-duration travel and medical cover for students abroad, including study interruption and sponsor protection.',
    featured: false,
    partnerIds: ['solaris'],
    icon: '🎓',
    coverage: { min: 5 * L, max: 60 * L, step: 5 * L, default: 20 * L },
    termOptions: [1, 2, 3],
    baseRatePerLakh: 240,
    benefits: [
      'Medical cover during studies',
      'Study interruption benefit',
      'Sponsor protection',
      'Compassionate visit cover',
    ],
    coverageDetails: [
      { label: 'Medical emergency', value: 'Up to sum insured' },
      { label: 'Study interruption', value: 'Tuition reimbursed' },
      { label: 'Sponsor protection', value: 'Covered' },
    ],
    exclusions: ['Pre-existing conditions', 'Self-inflicted injuries'],
    rating: 4.4,
    claimSettlementRatio: 94.0,
  },
]
